#!/usr/bin/env python3
"""Translate English typeNames to Chinese in zh-Hans JSON file."""

import json
import re

# English → Chinese typeName translations (plant care & botanical terminology)
TRANSLATIONS = {
    # Aglaonema / 广东万年青
    "Red Valentine Aglaonema": "红心万年青",
    "Maria Aglaonema": "玛丽亚万年青",
    "Silver Bay Aglaonema": "银湾万年青",
    "Aglaonema Pink Star": "粉星万年青",
    "Aglaonema Sparkling Sarah": "闪耀莎拉万年青",
    # Aralia
    "Ming Aralia": "孔雀木",
    "False Aralia": "假孔雀木",
    # Aspidistra / 一叶兰
    "Variegated Cast Iron": "斑叶一叶兰",
    # Palms
    "Bamboo Palm": "竹棕榈",
    "Parlor Palm": "袖珍椰",
    "Radicalis Palm": "竹椰棕榈",
    "Pygmy Date Palm": "袖珍枣椰",
    "Umbrella Plant": "伞树",
    # Dracaena / 龙血树
    "Compact Dumb Cane": "紧凑型花叶万年青",
    "Janet Craig Dracaena": "珍妮特克雷格龙血树",
    "Dracaena Limelight": "莱姆之光龙血树",
    "Dracaena Warneckii": "华纳克龙血树",
    "Song of India": "印度之歌",
    # Ficus
    "Weeping Fig": "垂叶榕",
    # Peace Lily
    "Peace Lily Sensation": "大叶白掌",
    "Domino Peace Lily": "多米诺白掌",
    # Peperomia
    "Peperomia Ginny": "彩虹边椒草",
    # Philodendron
    "Philodendron Congo": "刚果喜林芋",
    "Philodendron Scandens": "心叶喜林芋",
    "Philodendron Gloriosum": "荣耀蔓绿绒",
    "Philodendron Scandal": "心叶喜林芋攀爬型",
    "Philodendron Jose Buono": "何塞·布诺喜林芋",
    "Philodendron Mamei": "银云喜林芋",
    "Philodendron Melanochrysum": "黑金蔓绿绒",
    "Philodendron Plowmanii": "普洛曼喜林芋",
    "Prince of Orange": "橙色王子喜林芋",
    "Ring of Fire Philodendron": "火环喜林芋",
    "Tree Philodendron": "树状喜林芋",
    "Silver Philodendron": "银叶喜林芋",
    "Philodendron Verrucosum": "疣茎喜林芋",
    "White Knight Philodendron": "白骑士喜林芋",
    "White Wizard Philodendron": "白巫师喜林芋",
    "Philodendron Xanadu": "琴叶喜林芋",
    # Pilea
    "Silver Sparkle Pilea": "银星冷水花",
    # Pothos / 绿萝
    "Cebu Blue Pothos": "宿务蓝绿萝",
    "Jade Pothos": "翡翠绿萝",
    "Manjula Pothos": "曼朱拉绿萝",
    # Snake Plant
    "Moonshine Snake Plant": "月光虎尾兰",
    # Syngonium
    "White Butterfly": "白蝴蝶",
    "Syngonium Albo": "白锦合果芋",
    "Pink Syngonium": "粉叶合果芋",
    "Syngonium Pink Splash": "粉斑合果芋",
    # Alocasia / 海芋
    "Black Velvet Alocasia": "黑天鹅绒海芋",
    "Alocasia Cuprea": "铜叶海芋",
    "Alocasia Frydek": "绿丝绒海芋",
    "Alocasia Mahorani": "灰龙海芋",
    "Alocasia Polly": "非洲面具海芋",
    "Alocasia Stingray": "魟鱼海芋",
    "Alocasia Zebrina": "斑马海芋",
    # Anthurium / 红掌
    "Velvet Cardboard Anthurium": "丝绒纸板红掌",
    "Anthurium Magnificum": "壮丽红掌",
    "Strap Leaved Anthurium": "带状叶红掌",
    "Queen Anthurium": "女王红掌",
    # Dieffenbachia
    "Dieffenbachia Seguine": "花叶万年青原种",
    # Epipremnum
    "Epipremnum Pinnatum Albo": "白锦高锦绿萝",
    # Monstera
    "Monstera Albo": "白锦龟背竹",
    "Monstera Aurea": "黄锦龟背竹",
    "Monstera Peru": "秘鲁龟背竹",
    "Monstera Siltepecana": "银纹龟背竹",
    "Thai Constellation Monstera": "泰国繁星龟背竹",
    "Mini Monstera": "迷你龟背竹",
    # Zebra
    "Zebra Plant": "银脉爵床",
    # Ferns
    "Asparagus Fern": "文竹",
    "Deer Fern": "鹿角蕨",
    "Kangaroo Paw Fern": "袋鼠爪蕨",
    "Crocodile Fern": "鳄鱼蕨",
    "Lemon Button Fern": "柠檬钮蕨",
    "Blue Star Fern": "蓝星蕨",
    "Elkhorn Fern": "鹿角蕨",
    "Brake Fern": "凤尾蕨",
    "Cretan Brake Fern": "克里特凤尾蕨",
    # Succulents
    "Dwarf Jade": "迷你玉树",
    "African Milk Tree": "非洲乳树",
    "Paddle Plant": "宽叶落地生根",
    "Elephant Bush": "象脚树",
    "Burro's Tail": "玉缀",
    "String of Dolphins": "海豚吊兰",
    "Black Gem Aloe": "黑宝石芦荟",
    "Echeveria Lola": "洛拉拟石莲",
    "Echeveria Perle von Nurnberg": "紫珍珠拟石莲",
    "Haworthia Cooperi": "玉露",
    # Begonia
    "Begonia Maculata Wightii": "斑叶竹节秋海棠",
    # Croton / 变叶木
    "Croton Mammy": "妈妈变叶木",
    # Oxalis
    "Purple Shamrock": "紫酢浆草",
    # Peperomia
    "Emerald Ripple": "翡翠波纹椒草",
    "Baby Rubber Plant": "婴儿橡皮树",
    "Burgundy Rubber Plant": "酒红橡皮树",
    # Trees
    "Bald Cypress": "落羽杉",
    "Flowering Cherry": "樱花",
    "Crabapple": "海棠",
    "Crepe Myrtle": "紫薇",
    "Hornbeam": "鹅耳枥",
    "Japanese Maple": "日本枫",
    "Redbud": "紫荆",
    "Chinese Redbud": "中国紫荆",
    "River Birch": "河桦",
    "Serviceberry": "唐棣",
    "Smoke Tree": "黄栌",
    "Sweetgum": "枫香",
    "Weeping Willow": "垂柳",
    # Shrubs
    "Abelia": "六道木",
    "Barberry": "小檗",
    "Burning Bush": "卫矛",
    "Butterfly Bush": "醉鱼草",
    "Caryopteris": "莸",
    "Cotoneaster": "栒子",
    "Holly": "冬青",
    "Leadplant": "灰毛豆",
    "Loropetalum": "檵木",
    "Nandina": "南天竹",
    "Ninebark": "风箱果",
    "Rose of Sharon": "木槿",
    "Russian Sage": "俄罗斯鼠尾草",
    "Spirea": "绣线菊",
    # Vegetables, fruits, herbs, crops
    "Acorn Squash": "橡实南瓜",
    "Adzuki Sprouts": "红豆芽",
    "Alfalfa": "苜蓿",
    "Alfalfa Sprouts": "苜蓿芽",
    "Amaranth": "苋菜",
    "Amaranth Microgreens": "苋菜芽苗",
    "Armenian Cucumber": "亚美尼亚黄瓜",
    "Artichoke": "朝鲜蓟",
    "Arugula Microgreens": "芝麻菜芽苗",
    "Bahia Grass": "巴伊亚草",
    "Banana": "香蕉",
    "Barley": "大麦",
    "Basil Microgreens": "罗勒芽苗",
    "Bay Laurel": "月桂",
    "Beet Greens": "甜菜叶",
    "Beet Microgreens": "甜菜芽苗",
    "Bitter Melon": "苦瓜",
    "Broccoli Raab Microgreens": "西兰花苔芽苗",
    "Broccoli Sprouts": "西兰花芽",
    "Buckwheat": "荞麦",
    "Buckwheat Sprouts": "荞麦芽",
    "Cabbage Microgreens": "卷心菜芽苗",
    "Canola": "油菜",
    "Cape Gooseberry": "灯笼果",
    "Carrot Microgreens": "胡萝卜芽苗",
    "Cassava": "木薯",
    "Castor Bean": "蓖麻",
    "Celery Microgreens": "芹菜芽苗",
    "Chard Microgreens": "瑞士甜菜芽苗",
    "Cherry Tomato": "樱桃番茄",
    "Chickpea": "鹰嘴豆",
    "Chickpea Sprouts": "鹰嘴豆芽",
    "Chinese Eggplant": "中国茄子",
    "Cilantro Microgreens": "香菜芽苗",
    "Clover Sprouts": "三叶草芽",
    "Coconut": "椰子",
    "Cowpea": "豇豆",
    "Crenshaw Melon": "克伦肖甜瓜",
    "Dates": "椰枣",
    "Delicata Squash": "美味南瓜",
    "Dill Microgreens": "莳萝芽苗",
    "Endive": "菊苣",
    "Epazote": "土荆芥",
    "Escarole": "宽叶菊苣",
    "Fava Bean": "蚕豆",
    "Fennel Microgreens": "茴香芽苗",
    "Fenugreek Sprouts": "胡芦巴芽",
    "Field Corn": "大田玉米",
    "Flax": "亚麻",
    "Garden Cress": "庭院水芹",
    "Grain Amaranth": "籽粒苋",
    "Ground Cherry": "灯笼果",
    "Guava": "番石榴",
    "Honeydew": "蜜瓜",
    "Hops": "啤酒花",
    "Horseradish": "辣根",
    "Jerusalem Artichoke": "菊芋",
    "Jute": "黄麻",
    "Kale Microgreens": "羽衣甘蓝芽苗",
    "Kiwi": "猕猴桃",
    "Kohlrabi Microgreens": "苤蓝芽苗",
    "Lemon Cucumber": "柠檬黄瓜",
    "Lentil": "小扁豆",
    "Lentil Sprouts": "小扁豆芽",
    "Malabar Spinach": "落葵",
    "Mango": "芒果",
    "Millet": "小米",
    "Mizuna": "水菜",
    "Mizuna Microgreens": "水菜芽苗",
    "Mung Bean": "绿豆",
    "Mung Bean Sprouts": "绿豆芽",
    "Musk Melon": "香瓜",
    "Mustard": "芥菜",
    "Mustard Microgreens": "芥菜芽苗",
    "Oats": "燕麦",
    "Oil Sunflower": "油葵",
    "Olive": "橄榄",
    "Onion Sprouts": "洋葱芽",
    "Parsnip Microgreens": "欧洲防风芽苗",
    "Pattypan Squash": "飞碟南瓜",
    "Pea Shoots": "豌豆苗",
    "Peanut": "花生",
    "Pineapple": "菠萝",
    "Purslane": "马齿苋",
    "Quinoa": "藜麦",
    "Radicchio": "紫菊苣",
    "Radish Microgreens": "萝卜芽苗",
    "Rice": "水稻",
    "Roma Tomato": "罗马番茄",
    "Rye": "黑麦",
    "Safflower": "红花",
    "Salsify": "婆罗门参",
    "Sesame": "芝麻",
    "Sesame Sprouts": "芝麻芽",
    "Shiso": "紫苏",
    "Shiso Microgreens": "紫苏芽苗",
    "Snow Pea Sprouts": "荷兰豆芽",
    "Sorghum": "高粱",
    "Sorrel": "酸模",
    "Sorrel Microgreens": "酸模芽苗",
    "Soybean": "大豆",
    "Soybean Sprouts": "黄豆芽",
    "Spaghetti Squash": "意大利面南瓜",
    "Spinach Microgreens": "菠菜芽苗",
    "Stevia": "甜菊",
    "Sugar Beet": "糖用甜菜",
    "Sugarcane": "甘蔗",
    "Sunflower Sprouts": "葵花芽",
    "Sweet Potato": "甘薯",
    "Tall Fescue": "高羊茅",
    "Tatsoi": "塌棵菜",
    "Tatsoi Microgreens": "塌棵菜芽苗",
    "Teff": "苔麸",
    "Tobacco": "烟草",
    "Tomatillo": "墨西哥酸浆",
    "Turnip Greens": "芜菁叶",
    "Turnip Microgreens": "芜菁芽苗",
    "Vietnamese Coriander": "越南香菜",
    "Watercress Sprouts": "豆瓣菜芽",
    "Wheat": "小麦",
    "Wheatgrass": "小麦草",
    "Winter Melon": "冬瓜",
    "Yard Long Bean": "长豇豆",
    "Yellow Watermelon": "黄瓤西瓜",
    # Perennials & flowers
    "African Marigold": "非洲万寿菊",
    "Ajuga": "筋骨草",
    "Alpine Aster": "高山紫菀",
    "Alpine Bellflower": "高山风铃草",
    "Alpine Catchfly": "高山蝇子草",
    "Alpine Pink": "高山石竹",
    "Alpine Poppy": "高山罂粟",
    "Alyssum": "香雪球",
    "Anemone": "银莲花",
    "Angelonia": "天使花",
    "Asiatic Lily": "亚洲百合",
    "Astilbe": "落新妇",
    "Bacopa": "假马齿苋",
    "Bee Balm": "香蜂草",
    "Big Bluestem": "大蓝茎草",
    "Blanket Flower": "天人菊",
    "Blazing Star": "蛇鞭菊",
    "Bleeding Heart": "荷包牡丹",
    "Blue Fescue": "蓝羊茅",
    "Blue Grama": "蓝格兰马草",
    "Borage": "琉璃苣",
    "Butterfly Weed": "蝴蝶草",
    "Calibrachoa": "百万小铃",
    "Calla Lily": "马蹄莲",
    "Canna": "美人蕉",
    "Carolina Jessamine": "卡罗莱纳茉莉",
    "Casa Blanca Lily": "卡萨布兰卡百合",
    "Catmint": "荆芥",
    "Catnip": "猫薄荷",
    "Celeriac": "根芹菜",
    "Celosia": "鸡冠花",
    "Chamomile": "洋甘菊",
    "Chervil": "细叶芹",
    "China Pink": "石竹",
    "Climbing Hydrangea": "攀缘绣球",
    "Climbing Rose": "藤本月季",
    "Columbine": "耧斗菜",
    "Comfrey": "聚合草",
    "Common Milkweed": "普通乳草",
    "Common Zinnia": "百日菊",
    "Compass Plant": "指南植物",
    "Coreopsis": "金鸡菊",
    "Cornflower": "矢车菊",
    "Cotton": "棉花",
    "Creeping Sedum": "匍匐景天",
    "Creeping Thyme": "匍匐百里香",
    "Crossvine": "十字蔓",
    "Culver's Root": "佛沃根",
    "Currant": "醋栗",
    "Cyclamen": "仙客来",
    "Dahlia": "大丽花",
    "Dandelion Greens": "蒲公英叶",
    "Delphinium": "飞燕草",
    "Dianthus": "石竹属",
    "Draba": "葶苈",
    "Duckweed": "浮萍",
    "False Indigo": "假靛蓝",
    "Field Scabious": "田野蓝盆花",
    "Floating Heart": "睡莲",
    "Fountain Grass": "喷泉草",
    "Foxglove": "毛地黄",
    "Freesia": "小苍兰",
    "Fritillaria": "贝母",
    "Gaillardia": "天人菊属",
    "Garden Verbena": "花园马鞭草",
    "Giant Allium": "大花葱",
    "Glory of the Snow": "雪光花",
    "Goldenrod": "一枝黄花",
    "Gooseberry": "醋栗",
    "Grandiflora Petunia": "大花矮牵牛",
    "Great Mullein": "毛蕊花",
    "Hardy Geranium": "耐寒天竺葵",
    "Hens and Chicks": "长生草",
    "Heuchera": "矾根",
    "Holy Basil": "圣罗勒",
    "Indian Grass": "印第安草",
    "Ironweed": "斑鸠菊",
    "Joe Pye Weed": "斑叶泽兰",
    "Lamb's Ear": "绵毛水苏",
    "Lantana": "马缨丹",
    "Leek Sprouts": "韭葱芽",
    "Lemon Balm": "柠檬香蜂草",
    "Lewisia": "琉维草",
    "Lichen": "地衣",
    "Lily of the Valley": "铃兰",
    "Little Bluestem": "小蓝茎草",
    "Lobelia": "半边莲",
    "Loganberry": "罗甘莓",
    "Lovage": "独活草",
    "Lupine": "羽扇豆",
    "Marjoram": "马郁兰",
    "Maximilian Sunflower": "马克西米利安向日葵",
    "Meadow Cranesbill": "草地老鹳草",
    "Meadow Sage": "草地鼠尾草",
    "Miscanthus": "芒草",
    "Moss Rose": "松叶牡丹",
    "Mulberry": "桑树",
    "Muscari": "葡萄风信子",
    "New England Aster": "新英格兰紫菀",
    "Painted Daisy": "孔雀菊",
    "Pale Purple Coneflower": "淡紫松果菊",
    "Pansy": "三色堇",
    "Papaya": "番木瓜",
    "Papyrus": "纸莎草",
    "Passion Flower": "西番莲",
    "Passion Fruit": "百香果",
    "Pawpaw": "番木瓜",
    "Penstemon": "钓钟柳",
    "Pentas": "五星花",
    "Phlox": "福禄考",
    "Pink Muhly Grass": "粉黛乱子草",
    "Prairie Coneflower": "草原松果菊",
    "Prairie Dock": "草原酸模",
    "Prairie Dropseed": "草原垂穗草",
    "Prickly Pear Fruit": "仙人掌果",
    "Purple Coneflower": "紫松果菊",
    "Quince": "榅桲",
    "Ranunculus": "毛茛",
    "Rattlesnake Master": "响尾蛇草",
    "Red Clover": "红三叶",
    "Rock Jasmine": "岩石茉莉",
    "Saffron Crocus": "藏红花",
    "Savory": "香薄荷",
    "Saxifrage": "虎耳草",
    "Scilla": "绵枣儿",
    "Shasta Daisy": "滨菊",
    "Showy Goldenrod": "艳丽一枝黄花",
    "Side Oats Grama": "侧穗格兰马草",
    "Smooth Blue Aster": "平滑蓝紫菀",
    "Snapdragon": "金鱼草",
    "Snowdrop": "雪花莲",
    "Stonecrop": "景天",
    "Swamp Milkweed": "沼泽乳草",
    "Sweet Joe Pye": "甜泽兰",
    "Sweet Potato Vine": "甘薯藤",
    "Sweet Woodruff": "香车叶草",
    "Switchgrass": "柳枝稷",
    "Tarragon": "龙蒿",
    "Tiger Lily": "卷丹",
    "Tuberose": "晚香玉",
    "Umbrella Palm": "伞棕榈",
    "Verbena": "马鞭草",
    "Viola": "堇菜",
    "Water Hawthorn": "水金莲",
    "Water Hyacinth": "凤眼莲",
    "Water Lettuce": "水浮莲",
    "Water Lily": "睡莲",
    "Wax Begonia": "四季海棠",
    "Weigela": "锦带花",
    "Wild Bergamot": "野香蜂草",
    "Wild Indigo": "野靛蓝",
    "Yarrow": "西洋蓍草",
    "Yellow Coneflower": "黄松果菊",
    "Yew": "红豆杉",
    # Orchids & bromeliads
    "Dendrobium Orchid": "石斛兰",
    "Dutch Iris": "荷兰鸢尾",
    "Mexican Pitcher Plant": "墨西哥瓶子草",
    "Mini Calla Lily": "迷你马蹄莲",
    "Neoregelia Bromeliad": "彩叶凤梨",
    "Nepenthes": "猪笼草",
    "Oncidium Orchid": "文心兰",
    "Oriental Lily": "东方百合",
    "Oxalis Bulb": "酢浆草球根",
    "Oxeye Daisy": "牛眼菊",
    "Saffron Crocus": "藏红花",
    "Sarracenia": "瓶子草",
    "Cape Sundew": "好望角茅膏菜",
    "Spanish Moss": "西班牙苔藓",
    "Tillandsia Bromeliad": "铁兰凤梨",
    "Xerographica Air Plant": "空气凤梨",
    "Vanda Orchid": "万代兰",
    # Vines & climbers
    "Boston Ivy": "爬山虎",
    "Trumpet Honeysuckle": "喇叭忍冬",
    "Trumpet Vine": "凌霄花",
    "Virginia Creeper": "五叶地锦",
    # Berries
    "Boysenberry": "波森莓",
    # Other
    "Bugloss": "牛舌草",
    "Japanese Eggplant": "日本茄子",
    "Japanese Forest Grass": "日本森林草",
    "Timothy Grass": "梯牧草",
}

def has_latin_chars(s: str) -> bool:
    """Check if string contains Latin letters (needs translation)."""
    return bool(re.search(r'[A-Za-z]', s))

def main():
    filepath = "source/common_plants_language_zh-Hans.json"
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    translated = 0
    missing = []
    
    for entry in data:
        if not isinstance(entry, dict) or "typeName" not in entry:
            continue
        
        tn = entry["typeName"]
        if has_latin_chars(tn) and tn in TRANSLATIONS:
            entry["typeName"] = TRANSLATIONS[tn]
            translated += 1
        elif has_latin_chars(tn):
            missing.append(tn)
    
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Translated: {translated}")
    if missing:
        print(f"\nMissing translations ({len(missing)}):")
        for m in sorted(set(missing)):
            print(f"  - {m}")

if __name__ == "__main__":
    import os
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    main()
