#!/usr/bin/env python3
"""Translate English typeNames to Spanish in common_plants_language_es.json."""

import json
import re

# English → Spanish typeName translations (plant care & botanical terminology)
# Focus on common names; Latin genus names often kept in Spanish horticulture
TRANSLATIONS = {
    # Vegetables
    "Acorn Squash": "Calabaza bellota",
    "Armenian Cucumber": "Pepino armenio",
    "Artichoke": "Alcachofa",
    "Bitter Melon": "Melón amargo",
    "Bok Choy": "Bok choy",
    "Cherry Tomato": "Tomate cherry",
    "Chayote": "Chayote",
    "Chinese Eggplant": "Berenjena china",
    "Colocasia / Taro": "Colocasia / Taro",
    "Crenshaw Melon": "Melón Crenshaw",
    "Daikon": "Rábano daikon",
    "Delicata Squash": "Calabaza delicata",
    "Edamame": "Edamame",
    "Endive": "Endibia",
    "Epazote": "Epazote",
    "Escarole": "Escarola",
    "Ground Cherry": "Tomatillo",
    "Japanese Eggplant": "Berenjena japonesa",
    "Jerusalem Artichoke": "Aguaturma",
    "Lemon Cucumber": "Pepino limón",
    "Malabar Spinach": "Espinaca de Malabar",
    "Pattypan Squash": "Calabaza pattypan",
    "Salsify": "Salsifí",
    "Spaghetti Squash": "Calabaza espagueti",
    "Choy Sum": "Choy sum",
    "Gai Lan": "Gai lan",
    # Fruits
    "Banana": "Plátano",
    "Boysenberry": "Baya de Boysen",
    "Cape Gooseberry": "Uchuva",
    "Coconut": "Coco",
    "Crabapple": "Manzano silvestre",
    "Currant": "Grosella",
    "Dates": "Dátiles",
    "Goji Berry": "Baya de goji",
    "Gooseberry": "Grosella espinosa",
    "Guava": "Guayaba",
    "Honeydew": "Melón verde",
    "Kiwi": "Kiwi",
    "Kumquat": "Kumquat",
    "Loganberry": "Loganberry",
    "Longan": "Longan",
    "Mango": "Mango",
    "Mulberry": "Morera",
    "Pineapple": "Piña",
    "Quince": "Membrillo",
    # Herbs & spices
    "Basil Microgreens": "Microgreens de albahaca",
    "Bay Laurel": "Laurel",
    "Beet Greens": "Hojas de remolacha",
    "Cilantro": "Cilantro",
    "Cilantro Microgreens": "Microgreens de cilantro",
    "Epazote": "Epazote",
    "Holy Basil": "Albahaca sagrada",
    "Marjoram": "Mejorana",
    "Lovage": "Apio de monte",
    "Savory": "Ajedrea",
    "Tarragon": "Estragón",
    # Sprouts & microgreens
    "Adzuki Sprouts": "Brotes de adzuki",
    "Alfalfa Sprouts": "Brotes de alfalfa",
    "Amaranth Microgreens": "Microgreens de amaranto",
    "Arugula Microgreens": "Microgreens de rúcula",
    "Basil Microgreens": "Microgreens de albahaca",
    "Beet Microgreens": "Microgreens de remolacha",
    "Broccoli Raab Microgreens": "Microgreens de brócoli raab",
    "Broccoli Sprouts": "Brotes de brócoli",
    "Buckwheat Sprouts": "Brotes de trigo sarraceno",
    "Cabbage Microgreens": "Microgreens de col",
    "Carrot Microgreens": "Microgreens de zanahoria",
    "Celery Microgreens": "Microgreens de apio",
    "Chard Microgreens": "Microgreens de acelga",
    "Chickpea Sprouts": "Brotes de garbanzo",
    "Cilantro Microgreens": "Microgreens de cilantro",
    "Clover Sprouts": "Brotes de trébol",
    "Dill Microgreens": "Microgreens de eneldo",
    "Fennel Microgreens": "Microgreens de hinojo",
    "Fenugreek Sprouts": "Brotes de fenogreco",
    "Kale Microgreens": "Microgreens de col rizada",
    "Kohlrabi Microgreens": "Microgreens de colinabo",
    "Leek Sprouts": "Brotes de puerro",
    "Lentil Sprouts": "Brotes de lenteja",
    "Mizuna Microgreens": "Microgreens de mizuna",
    "Mung Bean Sprouts": "Brotes de frijol mungo",
    "Onion Sprouts": "Brotes de cebolla",
    "Parsnip Microgreens": "Microgreens de pastinaca",
    "Pea Shoots": "Brotes de guisante",
    "Radish Microgreens": "Microgreens de rábano",
    "Shiso Microgreens": "Microgreens de shiso",
    "Snow Pea Sprouts": "Brotes de guisante de nieve",
    "Sorrel Microgreens": "Microgreens de acedera",
    "Soybean Sprouts": "Brotes de soja",
    "Spinach Microgreens": "Microgreens de espinaca",
    "Sunflower Sprouts": "Brotes de girasol",
    "Tatsoi Microgreens": "Microgreens de tatsoi",
    "Turnip Microgreens": "Microgreens de nabo",
    "Watercress Sprouts": "Brotes de berro",
    "Wheatgrass": "Pasto de trigo",
    # Crops & grains
    "Alfalfa": "Alfalfa",
    "Amaranth": "Amaranto",
    "Barley": "Cebada",
    "Buckwheat": "Trigo sarraceno",
    "Canola": "Colza",
    "Castor Bean": "Ricino",
    "Cassava": "Yuca",
    "Chickpea": "Garbanzo",
    "Cowpea": "Caupí",
    "Field Corn": "Maíz de campo",
    "Flax": "Lino",
    "Fava Bean": "Haba",
    "Grain Amaranth": "Amaranto de grano",
    "Jute": "Yute",
    "Lentil": "Lenteja",
    "Millet": "Mijo",
    "Mung Bean": "Frijol mungo",
    "Oats": "Avena",
    "Peanut": "Cacahuete",
    "Quinoa": "Quinoa",
    "Rice": "Arroz",
    "Rye": "Centeno",
    "Sesame": "Sésamo",
    "Sorghum": "Sorgo",
    "Soybean": "Soja",
    "Sugar Beet": "Remolacha azucarera",
    "Sugarcane": "Caña de azúcar",
    "Teff": "Teff",
    "Tobacco": "Tabaco",
    "Wheat": "Trigo",
    # Ornamentals - trees & shrubs
    "Abelia": "Abelia",
    "Barberry": "Agracejo",
    "Burning Bush": "Euonymus",
    "Butterfly Bush": "Buddleia",
    "Chinese Redbud": "Redbud chino",
    "Cotoneaster": "Cotoneaster",
    "Crabapple": "Manzano silvestre",
    "Holly": "Acebo",
    "Hornbeam": "Carpe",
    "Loropetalum": "Loropetalum",
    "Magnolia": "Magnolia",
    "Nandina": "Nandina",
    "Rose of Sharon": "Rosa de Sharon",
    "Russian Sage": "Salvia rusa",
    "Weigela": "Weigela",
    "Yew": "Tejo",
    # Ornamentals - perennials & flowers
    "African Marigold": "Tagete africano",
    "Ajuga": "Búgula",
    "Alpine Aster": "Áster alpino",
    "Alpine Bellflower": "Campánula alpina",
    "Alpine Catchfly": "Silene alpina",
    "Alpine Pink": "Clavel alpino",
    "Alpine Poppy": "Amapola alpina",
    "Alyssum": "Aliso",
    "Anemone": "Anémona",
    "Angelonia": "Angelonia",
    "Astilbe": "Astilbe",
    "Bacopa": "Bacopa",
    "Bee Balm": "Monarda",
    "Blanket Flower": "Gaillardia",
    "Bleeding Heart": "Corazón sangrante",
    "Borage": "Borraja",
    "Butterfly Weed": "Algodoncillo",
    "Calibrachoa": "Calibrachoa",
    "Calla Lily": "Cala",
    "Canna": "Canna",
    "Caryopteris": "Cariopteris",
    "Catnip": "Nepeta",
    "Celosia": "Celosia",
    "Chamomile": "Manzanilla",
    "Chervil": "Perifollo",
    "China Pink": "Clavel chino",
    "Climbing Hydrangea": "Hortensia trepadora",
    "Climbing Rose": "Rosa trepadora",
    "Columbine": "Aquileña",
    "Comfrey": "Consuelda",
    "Common Milkweed": "Algodoncillo común",
    "Common Zinnia": "Zinnia común",
    "Coreopsis": "Coreopsis",
    "Cosmos": "Cosmos",
    "Cotton": "Algodón",
    "Creeping Sedum": "Sedum rastrero",
    "Creeping Thyme": "Tomillo rastrero",
    "Crossvine": "Bignonia",
    "Culver's Root": "Raíz de Culver",
    "Cyclamen": "Ciclamen",
    "Dahlia": "Dalia",
    "Dandelion Greens": "Hojas de diente de león",
    "Delphinium": "Delfinio",
    "Dianthus": "Dianthus",
    "Dutch Iris": "Iris holandés",
    "Edelweiss": "Edelweiss",
    "False Indigo": "Falso índigo",
    "Field Scabious": "Escabiosa de campo",
    "Foxglove": "Dedalera",
    "Freesia": "Fresia",
    "Fritillaria": "Fritilaria",
    "Gaillardia": "Gaillardia",
    "Garden Cress": "Berro de jardín",
    "Garden Verbena": "Verbena de jardín",
    "Giant Allium": "Allium gigante",
    "Glory of the Snow": "Quionodoxa",
    "Goldenrod": "Vara de oro",
    "Grandiflora Petunia": "Petunia grandiflora",
    "Hardy Geranium": "Geranio resistente",
    "Hens and Chicks": "Siémpreviva",
    "Heuchera": "Heuchera",
    "Ironweed": "Hierba del hierro",
    "Joe Pye Weed": "Eupatorio",
    "Lamb's Ear": "Oreja de cordero",
    "Lantana": "Lantana",
    "Lemon Balm": "Toronjil",
    "Lily of the Valley": "Lirio de los valles",
    "Lobelia": "Lobelia",
    "Lupine": "Lupino",
    "Marjoram": "Mejorana",
    "Maximilian Sunflower": "Girasol Maximiliano",
    "Mexican Pitcher Plant": "Planta jarra mexicana",
    "Miscanthus": "Miscanto",
    "Moss Rose": "Rosa musgo",
    "Muscari": "Muscari",
    "Painted Daisy": "Margarita pintada",
    "Pansy": "Pensamiento",
    "Papaya": "Papaya",
    "Papyrus": "Papiro",
    "Passion Flower": "Flor de la pasión",
    "Passion Fruit": "Maracuyá",
    "Pawpaw": "Asimina",
    "Penstemon": "Penstemon",
    "Pentas": "Pentas",
    "Phlox": "Phlox",
    "Prickly Pear Fruit": "Fruto de nopal",
    "Ranunculus": "Ranúnculo",
    "Red Clover": "Trébol rojo",
    "Saffron Crocus": "Azafrán",
    "Shasta Daisy": "Margarita Shasta",
    "Snapdragon": "Antirrino",
    "Snowdrop": "Campanilla de invierno",
    "Stonecrop": "Uva de gato",
    "Swamp Milkweed": "Algodoncillo de pantano",
    "Sweet Woodruff": "Galio",
    "Tiger Lily": "Lirio tigre",
    "Tuberose": "Nardo",
    "Verbena": "Verbena",
    "Viola": "Viola",
    "Water Lily": "Nenúfar",
    "Wax Begonia": "Begonia de cera",
    "Wild Bergamot": "Monarda silvestre",
    "Yarrow": "Milenrama",
    # Houseplant common names
    "Ming Aralia": "Aralia Ming",
    "Begonia": "Begonia",
    "Calla Lily": "Cala",
    "Clivia": "Clivia",
    "Croton": "Croton",
    "Dieffenbachia": "Dieffenbachia",
    "Gardenia": "Gardenia",
    "Hostas": "Hostas",
    "Impatiens": "Impatiens",
    # Vines & climbers
    "Boston Ivy": "Hiedra de Boston",
    "Carolina Jessamine": "Jazmín de Carolina",
    "Trumpet Honeysuckle": "Madreselva trompeta",
    "Trumpet Vine": "Enredadera trompeta",
    "Virginia Creeper": "Parra virgen",
    # Grasses & groundcovers
    "Bahia Grass": "Pasto bahía",
    "Blue Fescue": "Festuca azul",
    "Blue Grama": "Grama azul",
    "Big Bluestem": "Andropogon grande",
    "Fountain Grass": "Hierba de fuentes",
    "Japanese Forest Grass": "Hierba del bosque japonés",
    "Little Bluestem": "Andropogon pequeño",
    "Pink Muhly Grass": "Muhlenbergia rosa",
    "Side Oats Grama": "Grama lateral",
    "Switchgrass": "Panicum",
    "Tall Fescue": "Festuca alta",
    "Timothy Grass": "Fleo",
    # Aquatic & specialty
    "Duckweed": "Lenteja de agua",
    "Floating Heart": "Corazón flotante",
    "Water Hawthorn": "Espino de agua",
    "Water Hyacinth": "Jacinto de agua",
    "Water Lettuce": "Lechuga de agua",
    "Cape Sundew": "Rocío del Cabo",
    "Spanish Moss": "Musgo español",
    "Lichen": "Liquen",
    # Other
    "Bugloss": "Anchusa",
    "Celeriac": "Apio nabo",
    "Dandelion Greens": "Hojas de diente de león",
    "Ginkgo": "Ginkgo",
    "Goji Berry": "Baya de goji",
    "Habanero": "Habanero",
    "Hops": "Lúpulo",
    "Horseradish": "Rábano picante",
    "Jalapeño": "Jalapeño",
    "Mizuna": "Mizuna",
    "Mustard": "Mostaza",
    "Purslane": "Verdolaga",
    "Shiso": "Shiso",
    "Sorrel": "Acedera",
    "Stevia": "Estevia",
    "Tatsoi": "Tatsoi",
    "Turnip Greens": "Hojas de nabo",
    "Vietnamese Coriander": "Cilantro vietnamita",
    "Winter Melon": "Melón de invierno",
    "Yellow Watermelon": "Sandía amarilla",
}


def main():
    filepath = "source/common_plants_language_es.json"
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    translated = 0
    for entry in data:
        if not isinstance(entry, dict) or "typeName" not in entry:
            continue

        tn = entry["typeName"]
        if tn in TRANSLATIONS:
            entry["typeName"] = TRANSLATIONS[tn]
            translated += 1

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Translated: {translated}")


if __name__ == "__main__":
    import os

    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    main()
